/****************************************************************************
 *
 * Copyright (c) 2012 MediaTek Inc. All Rights Reserved.
 * --------------------
 * This software is protected by copyright and the information contained
 * herein is confidential. The software may not be copied and the information
 * contained herein may not be used or disclosed except with the written
 * permission of MediaTek Inc.
 *
 ****************************************************************************/

/****************************************************************************
 *       This file has been automatically generated by genmemfiles.py       *
 *    Any manual modifications will be lost when the file is regenerated    *
 ****************************************************************************/

#ifndef MEMFILESOURCE_A3M_H
#define MEMFILESOURCE_A3M_H

#include <a3m/memorystream.h> /* for MemoryStream and MemoryStreamSource */

a3m::MemoryStreamSource::Ptr create_memfilesource_a3m();

#endif // MEMFILESOURCE_A3M_H
