#!/bin/bash
rm cscope.out
rm tags
rm cscope.in.out
rm cscope.po.out
find . -name "*.h" -o -name "*.c" -o -name "*.cc" -o -name "*.cpp" -o -name "*.mk" -o -name "*.java" -o -name "*.aidl" -o -name "*.xml"> cscope.files
cscope -bkq -i cscope.files
ctags -L cscope.files
