/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

/////////////////////////////////////////////////////////////////////////////////////////
	MSG_ID_MMI_SS_MTLR_BEGIN_IND,
	MSG_ID_MMI_SS_MTLR_BEGIN_RES_REQ,
	MSG_ID_MMI_SS_MTLR_BEGIN_RES_RSP,
	MSG_ID_MMI_SS_AERQ_BEGIN_IND,
	MSG_ID_MMI_SS_AERQ_BEGIN_RES_REQ,
	MSG_ID_MMI_SS_AERQ_BEGIN_RES_RSP,
	MSG_ID_MMI_SS_AERP_BEGIN_REQ,
	MSG_ID_MMI_SS_AERP_BEGIN_RSP,
	MSG_ID_MMI_SS_AERP_END_REQ,
	MSG_ID_MMI_SS_AERP_END_RSP,
	MSG_ID_MMI_SS_AECL_BEGIN_IND,
	MSG_ID_MMI_SS_AECL_BEGIN_RES_REQ,
	MSG_ID_MMI_SS_AECL_BEGIN_RES_RSP,
	MSG_ID_MMI_SS_MOLR_BEGIN_REQ,
	MSG_ID_MMI_SS_MOLR_BEGIN_RSP,
	MSG_ID_MMI_SS_MOLR_END_REQ,
	MSG_ID_MMI_SS_MOLR_END_RSP,
	MSG_ID_MMI_AGPS_ENABLE_DISABLE_REQ,
	MSG_ID_MMI_AGPS_ENABLE_DISABLE_RSP,
	MSG_ID_MMI_AGPS_KEY_UPDATE_REQ,
	MSG_ID_MMI_AGPS_KEY_UPDATE_RSP,
	MSG_ID_MMI_AGPS_NEW_KEY_NEEDED_IND,
	MSG_ID_MMI_AGPS_RESET_POSITIONING_IND,
	MSG_ID_MMI_AGPS_CP_START_IND,
	MSG_ID_MMI_AGPS_CP_END_IND,
	MSG_ID_MMI_AGPS_CP_ABORT_REQ,
	MSG_ID_MMI_AGPS_CP_ABORT_RSP,
#if _FP_CR_SYNC_MAUI_03018028_ != 0
	MSG_ID_SP_L4C_NBR_CELL_INFO_REG_REQ,   // We can not use MSG_ID_L4C_NBR_CELL_INFO_REG_REQ because it is already defined in Typedef.h
	MSG_ID_SP_L4C_NBR_CELL_INFO_REG_CNF,
	MSG_ID_SP_L4C_NBR_CELL_INFO_DEREG_REQ,
	MSG_ID_SP_L4C_NBR_CELL_INFO_DEREG_CNF,
	MSG_ID_SP_L4C_NBR_CELL_INFO_IND,
#endif
	MSG_ID_AGPS_CONTROL_PLANE_20_END,
//////////////////////////////////////////////////////////////////////////////////////////

