#ifndef __SENSORD_VERSION_H
#define __SENSORD_VERSION_H
#define	SENSORD_MAIN_VERSION	3
#define	SENSORD_PATCHLEVEL	0
#define	SENSORD_SUBLEVEL	1
#define	SENSORD_EXTRAVERSION	12
#define SENSORD_VERSION ( (SENSORD_MAIN_VERSION << 24) |\
		(SENSORD_PATCHLEVEL << 16) |\
		(SENSORD_SUBLEVEL << 8) |\
		SENSORD_EXTRAVERSION )

#define	SENSORD_RLS_TIME	"2012-07-31,15:22:30"
#define	SENSORD_RLS_INFO	"@RI_20120731"
#endif
