/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2006
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *  supl_ulp_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file contains definitions used in supl_ulp_hdlr.c.
 *
 * Author:
 * -------
 *  Leo Hu
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Log$
 *
 * 06 19 2012 archilis.wang
 * [ALPS00303520] [Merge] Level 3 SW modules 提升至 Level 2 on ALPS.ICS2.MP
 * [Merge] Level 3 SW modules 提升至 Level 2 on ALPS.ICS2.MP
 *
 * May 2 2008 mtk00563
 * [MAUI_00763856] [AGPS] revise SUPL trace info.
 * 
 *
 * Apr 18 2008 mtk00563
 * [MAUI_00759106] [AGPS] Check-in AGPS feature.
 * 
 *
 * Mar 1 2008 mtk00563
 * [MAUI_00726103] [NOKIA MA] MMI shows incorrect message content
 * 
 *
 * Feb 25 2008 mtk00563
 * [MAUI_00623349] [AGPS] AGPS feature check-in
 * 
 *
 * 
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef _SUPL_ULP_DEF_H
#define _SUPL_ULP_DEF_H

#define     SUPL_NET_INFO_GSM       0x0000
#define     SUPL_NET_INFO_HISTORIC  0x0001
#define     SUPL_NET_INFO_NON_SERV  0x0002

typedef enum
{
    SUPL_ULP_MSG_UNKNOWN,
    SUPL_ULP_MSG_SUPL_INIT,
    SUPL_ULP_MSG_SUPL_START,
    SUPL_ULP_MSG_SUPL_RESPONSE,
    SUPL_ULP_MSG_SUPL_POS_INIT,
    SUPL_ULP_MSG_SUPL_POS,
    SUPL_ULP_MSG_SUPL_END,
#if 0 //__ULP_VER_1_5__
    SUPL_ULP_MSG_SUPL_TRIGGERED_START,
    SUPL_ULP_MSG_SUPL_TRIGGERED_RESPONSE,
    SUPL_ULP_MSG_SUPL_REPORT,
    SUPL_ULP_MSG_SUPL_NOTIFY,
    SUPL_ULP_MSG_SUPL_NOTIFY_RESPONSE,
#endif

    /* Please add SUPL_ULP_MSG_XXX before here */
    SUPL_ULP_MSG_INVALID,
    SUPL_ULP_MSG_END
} supl_ulp_msg_type_enum;

typedef enum
{
    SUPL_PROTO_ERR_UNSUPPORTED_VERSION,
    SUPL_PROTO_ERR_INVALID_SET_SESSION_ID,
    SUPL_PROTO_ERR_INVALID_SLP_SESSION_ID,
    SUPL_PROTO_ERR_NO_SET_SESSION_ID,
    SUPL_PROTO_ERR_NO_SLP_SESSION_ID,
    SUPL_PROTO_ERR_UNEXPECT_SET_SESSION_ID,
    SUPL_PROTO_ERR_UNEXPECT_SLP_SESSION_ID,
    SUPL_PROTO_ERR_MISSING_PARAMETER,
    SUPL_PROTO_ERR_INCORRECT_PARAMETER,
    SUPL_PROTO_ERR_UNEXPECT_MSG,
    SUPL_PROTO_ERR_POS_PROTOCOL_NOT_SUPPORT,
    SUPL_PROTO_ERR_NON_PROXY_MODE_NOT_SUPPORT,
    SUPL_PROTO_ERR_PROXY_MODE_NOT_SUPPORT,
    SUPL_PROTO_ERR_END
} supl_proto_err_enum;

typedef enum
{
    SUPL_ULP_STATUS_NORMAL,
    SUPL_ULP_STATUS_SYSTEM_FAILURE,
    SUPL_ULP_STATUS_UNSPECIFIED,
    SUPL_ULP_STATUS_PROTOCOL_ERROR,
    SUPL_ULP_STATUS_DATA_MISSING,
    SUPL_ULP_STATUS_UNEXPECTED_DATA_VALUE,
    SUPL_ULP_STATUS_POS_METHOD_FAILURE,
    SUPL_ULP_STATUS_POS_METHOD_MISMATCH,
    SUPL_ULP_STATUS_POS_PROTOCOL_MISMATCH,
    SUPL_ULP_STATUS_TARGET_SET_NOT_REACHABLE,
    SUPL_ULP_STATUS_VERSION_NOT_SUPPORTED,
    SUPL_ULP_STATUS_RESOURCE_SHORTAGE,
    SUPL_ULP_STATUS_INVALID_SESSION_ID,
    SUPL_ULP_STATUS_UNEXPECTED_MESSAGE,
    SUPL_ULP_STATUS_NON_PROXY_MODE_NOT_SUPPORTED,
    SUPL_ULP_STATUS_PROXY_MODE_NOT_SUPPORTED,
    SUPL_ULP_STATUS_POSITIONING_NOT_PERMITTED,
    SUPL_ULP_STATUS_AUTH_NET_FAILURE,
    SUPL_ULP_STATUS_AUTH_SUPL_INIT_FAILURE,
    SUPL_ULP_STATUS_CONSENT_DENIED_BY_USER,
    SUPL_ULP_STATUS_CONSENT_GRANTED_BY_USER,
    SUPL_ULP_STATUS_END
} supl_ulp_status_enum;

typedef enum
{
    SUPL_ULP_DECODE_FAIL_NONE,
    SUPL_ULP_DECODE_FAIL_HEADER,
    SUPL_ULP_DECODE_FAIL_LENGTH,
    SUPL_ULP_DECODE_FAIL_POS_PROTO,
    SUPL_ULP_DECODE_FAIL_POS_METHOD = 138,
    SUPL_ULP_DECODE_FAIL_NOTIFY_TYPE,
    SUPL_ULP_DECODE_FAIL_NOTIFY_ENCODING_TYPE,
    SUPL_ULP_DECODE_FAIL_NOTIFY_CLIENT_TYPE,
    SUPL_ULP_DECODE_FAIL_NOTIFY_REQUESTOR_TYPE,
    SUPL_ULP_DECODE_FAIL_SLP_ADDR_IPV6,
    SUPL_ULP_DECODE_FAIL_UNDEFINED,
    SUPL_ULP_DECODE_FAIL_END
} supl_ulp_decode_fail_enum;

typedef enum
{
    SUPL_ULP_RETCODE_OUTOFRADIOCOVERAGE,
    SUPL_ULP_RETCODE_NOPOSITION,
    SUPL_ULP_RETCODE_NOMEASUREMENT,
    SUPL_ULP_RETCODE_NOPOSITIONNOMEASUREMENT,
    SUPL_ULP_RETCODE_OTHER,
    SUPL_ULP_RETCODE_END
} supl_ulp_ret_code_enum;


#endif /* _SUPL_ULP_DEF_H */

