/*
 * Copyright (C) 2011 ALPS ELECTRIC CO., LTD. All Rights Reserved.
 *           This file must be operated as  based on the NDA (Non-Disclosure Agreement)
 *            with  ALPS ELECTRIC CO., LTD 
 *
 */
#ifndef ACDSINST_H_
#define ACDSINST_H_
MACM_EXTERN PTACDWK MACM_API SAcdGetInst(void);MACM_EXTERN TACDERR MACM_API SAcdInit(TInt SnsLv,TInt MPow,TInt Fukkaku,TInt 
Henkaku,PTAny CbParam,void (MACM_CALLBACK *cbNtcEvt )(TACDEVT evt,TInt32 ip,PTAny vp,PTAny CbParam),void (MACM_CALLBACK *
cbNtcRaw )(TACDSNS snsCode,TInt x,TInt y,TInt z,PTAny CbParam),void (MACM_CALLBACK *cbNtcFilt)(TACDSNS snsCode,TInt x,TInt y,
TInt z,PTAny CbParam));MACM_EXTERN TACDERR MACM_API SAcdGetRunList (PTACDRUNLIST pState);MACM_EXTERN TACDERR MACM_API 
SAcdGetParam (PTACDPARAM pBuf);MACM_EXTERN TACDERR MACM_API SAcdSetParam (PCTACDPARAM pParam);MACM_EXTERN TACDERR MACM_API 
SAcdSetAccGain (TInt gain);MACM_EXTERN TACDERR MACM_API SAcdGetCalibInfo (PTACDCALIBINFO pBuf);MACM_EXTERN TACDERR MACM_API 
SAcdSetCalibInfo (PCTACDCALIBINFO pInfo);MACM_EXTERN TACDERR MACM_API SAcdCl3d (TACDACT act);MACM_EXTERN TACDERR MACM_API 
SAcdDir3d (TACDACT act);
#ifdef ACDOPT_USEGYRO
MACM_EXTERN TACDERR MACM_API SAcdGyro (TACDACT act);
#endif
MACM_EXTERN TACDERR MACM_API SAcdInc (TACDACT act);MACM_EXTERN TACDERR MACM_API SAcdStopAll (void);MACM_EXTERN TACDERR MACM_API
SAcdGet3dAzimuth (PTInt pDir);MACM_EXTERN TACDERR MACM_API SAcdGet3dAttitude (PTInt pPitch,PTInt pRoll);MACM_EXTERN TACDERR 
MACM_API SAcdSet3dAttitude (TInt Pitch,TInt Roll);MACM_EXTERN TACDERR MACM_API SAcdSetAziLmtRNoChk (TBool flag);MACM_EXTERN 
TACDERR MACM_API SAcdPutSnsVal (TInt x,TInt y,TInt z);MACM_EXTERN TACDERR MACM_API SAcdPutAccVal (TInt x,TInt y,TInt z);
#ifdef ACDOPT_CLBSRH
MACM_EXTERN TACDERR MACM_API SAcdPutFixedCalibData (PTACD3DVEC pSns,TInt32 nSns);MACM_EXTERN TACDERR MACM_API 
SAcdPutFixedCalibDataEx(PTACD3DVEC pSns,TInt32 nSns);
#endif
MACM_EXTERN TACDERR MACM_API SAcdSetDefaultCalibParam(TInt SnsPeriod,TInt ClbPrec);
#ifdef ACDOPT_CLBSRH
MACM_EXTERN TBool MACM_API SAcdClSrh(PTACDC3S_CORBUF pBuf,TInt32 xc,TInt32 yc,TInt32 zc,TInt32 r,TInt times,PTACDCLBSRH pRsu);
MACM_EXTERN TBool MACM_API SAcdClMbCalc(PTACDC3S_CORBUF pBuf,PTACDCLBSRH pRsu);MACM_EXTERN TInt MACM_API SAcdClCorInit (
PTACDC3S_CORBUF pBuf,TInt32 xc,TInt32 yc,TInt32 zc,TInt32 r,TInt32 vDiv,TInt32 pol);MACM_EXTERN TBool MACM_API SAcdClCorPutVal(
PTACDC3S_CORBUF pBuf,PCTACD3DVEC pDat,PTInt pRatio,PTInt pPlots);MACM_EXTERN TInt MACM_API SAcdClCorGetAll(PTACDC3S_CORBUF pBuf
,PTACD3DVEC pDat,TInt nDat);MACM_EXTERN TBool MACM_API SAcdClCorGetFirst(PTACDC3S_CORBUF pBuf,PTACD3DVEC pDat);MACM_EXTERN 
TBool MACM_API SAcdClCorGetNext (PTACDC3S_CORBUF pBuf,PTACD3DVEC pDat);MACM_EXTERN PTACDC3S_CORBUF MACM_API SAcdClGetBufP(
TInt32 BufId);MACM_EXTERN TACDERR MACM_API SAcdStartEllipseCalib(TBool fStart);
#endif
#endif

