/**************************************************************************
 *
 * Copyright (c) 2012 MediaTek Inc. All Rights Reserved.
 * --------------------
 * This software is protected by copyright and the information contained
 * herein is confidential. The software may not be copied and the information
 * contained herein may not be used or disclosed except with the written
 * permission of MediaTek Inc.
 **************************************************************************/
/** \file
 * Doxygen top-level document structure (Text only, no code).
 */

/* Important Note

This file is special - it contains those those items that are unique in
configuration or content to a particular single build.

It contains sections such as mainpage that must be unique within a doxygen
build. It also contains stubs for document sets that are not included in the
build - e.g. generic MAGE components that are being used in this manual need to
have a 'mage' group but that is normally in a MAGE doxygen file.

*/


/*************************************************************************
 * Opening Page
 * Explain what NGIN3D is, and what it's for.
 *************************************************************************/

/** \mainpage Ngin3D: 3D Graphics for Android UI

\section ngin3d Introduction

Ngin3D enables fast development of 3D Android user interfaces.

\image html title_page_01.png

Ngin3D is part of the \ref mage "MediaTek Android Graphics Environment" known as
\ref mage "MAGE". Ngin3D provides the integration between the user UI
applications, Android infrastructure including threading, interpreting JSON
animations generated by Adobe AfterEffects, and the core A3M 3D Graphics engine.

<h2>Reading List</h2>
\b Essential:
- \ref a3mPrimer

Recommended:
- \ref nginTutor

Reference:
- \ref a3mJusr "Java API between Ngin3D and A3M"
- \ref glossary


\section mage MAGE

This diagram illustrates where Ngin3D fits into MAGE.  MAGE also includes
MediaTek's A3M graphics engine and support for both Adobe AfterEffects for
animation, and Autodesk 3DSMax for animated 3D models and scenes.

\image html mage_units_01.png "A3M as part of MAGE"

\section a3m A3M Graphics Engine

A3M (Advanced 3D Middleware) is a compact and highly flexible 3D graphics engine
built on top of OpenGL ES 2.x.  It is specifically designed for use in embedded
environments.

A3M is not specfic to Android and may be deployed on other OS's and platforms
(it \e is used in the PC tool Gloviewer). The Android Java API overlays a native
C++ API and A3M can be used in pure C++ environments. A3M fully supports
programmable-pipeline GPU graphics.

Documentation for A3M's Java API (used by Ngin3D) is included \ref a3mJusr
"here". Technical and C++ documentation for A3M is supplied separately.

<hr>

\note This documentation, and some of the code, uses a mixture of English
(<i>centre, colour</i>) and American (<i>center, color</i>) spellings.  Where
this is important within the code there may be an alias defined so that it
does not matter which you use, but this is not guaranteed.

*/


/*************************************************************************
 * Glossary entry point, also A3M stub
 *************************************************************************/
/** \defgroup glossary Glossary

Glossary of terms.

*/


/*************************************************************************
 * 2nd Level Ngin3D Groups
 *************************************************************************/


/** \defgroup ngin3dClasses Ngin3D Java Classes

Ngin3d Java classes.

*/

/** \defgroup ngin3dDemos Ngin3D Java Demos

Ngin3d Java example code.

*/


/* END OF FILE */


