/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
 *****************************************************************************
 * Filename:
 * --------------------------------------------------------
 *   asn_memory.h
 *
 * Project:
 * --------------------------------------------------------
 *   MONZA
 *
 * Description:
 * --------------------------------------------------------
 *   Autogenerated file using the ubiasn1_for_csi.bat.
 *
 * Author:
 * --------------------------------------------------------
 *   Jethro E. Lee
 *
 ****************************************************************************/
 
/****************************************************************************
 *
 *               Assignment : 3G
 *               (C) Ubinetics Ltd. 2002
 *               Cambridge Technology Centre
 *               Melbourn Royston
 *               Herts SG8 6DP UK
 *               Tel: +44 1763 262222
 *
 ****************************************************************************
 *
 * COMPONENT:    PLA
 * MODULE:       $RCSfile: $
 * VERSION:      $Revision: 1.3 $
 * DATED:        $Date: $
 * AUTHOR:       
 *
 * DESCRIPTION:  Memory managmenet API for UBIASN.1 runtime
 *
 ****************************************************************************/
/*****************************************************************************
 * $Log:$
 *
 * 06 19 2012 archilis.wang
 * [ALPS00303520] [Merge] Level 3 SW modules 提升至 Level 2 on ALPS.ICS2.MP
 * [Merge] Level 3 SW modules 提升至 Level 2 on ALPS.ICS2.MP
 *
 * Feb 25 2010 mtk80242
 * [MAUI_02155058] [asn.1]check-in w10.09
 * 
 *
 * Apr 7 2009 mtk01370
 * [MAUI_01659677] [asn.1]release 2.2.8 solve asnmemcopy and const and pMemFreeFunc issue
 * 
 *
 * Mar 4 2009 mtk01355
 * [MAUI_01641136] [MT6268A][UAS][USIME] New ASN IE handling is introduced for multiple band supporting
 * Band VIII above capability IE handler
 *
 * Jul 16 2008 mtk01370
 * [MAUI_00805735] [ASN]check in ASN common file in asn_re folder
 * 
 *
 * Sep 8 2007 mtk01355
 * [MAUI_00543985] [MAUI][UAS][DBME] merge to maintrunk
 * Merge newest MONZA29E4 change to MAUI
 *
 * Sep 7 2007 mtk01355
 * [MAUI_00543981] [MAUI][UAS][ASN] merge to maintrunk from MONZA branch
 * UAS ASN associated files merge to MAUI maintrunk
 *
 * Aug 6 2007 mtk01760
 * [MAUI_00527754] [Build Environment] Merge MONZA29E4 to MAUI
 * Add copyright header.
 ****************************************************************************/
  
#ifndef _ASNMEMORY_H
#define _ASNMEMORY_H

extern void asnMemSetMaxSizeTolerance(unsigned int maxlength);
extern unsigned int asnMemGetMaxSizeTolerance(void);

extern void asnMemCopy (void *pDest, const void *pSource, U32 uLen);

//extern void asnMemAlloc (void **memPtr, unsigned int size);
extern  void  asnMemAlloc(void *pContext, void ** ppBuffer, unsigned long uLen);
extern void asnMemFree (void **memPtr);

#endif /* _ASNMEMORY_H */

