/**************************************************************************
 *
 * Copyright (c) 2012 MediaTek Inc. All Rights Reserved.
 * --------------------
 * This software is protected by copyright and the information contained
 * herein is confidential. The software may not be copied and the information
 * contained herein may not be used or disclosed except with the written
 * permission of MediaTek Inc.
 **************************************************************************/
/** \file
 * Doxygen front page (Text only, no code).
 */

/* Important Note

This file is special - it contains those those items that are unique in
configuration or content to a particular single build. i.e. ALL the sections
here will need to have equivalents in a corresponding file for use with each
build.

It contains sections such as mainpage that must be unique within a doxygen
build. It also contains stubs for document sets that are not included in the
build - e.g. generic MAGE components that are being used in this manual need to
have a 'mage' group but that is normally in a MAGE doxygen file.

*/

/* Note there is no longer any Top Level "a3m" group. Link any 2nd-level
 * groups directly to the mainpage.
 */

/*************************************************************************
 * Opening Page
 * Explain what A3M is, and what it's for.
 *
 * There can be only one mainpage in a doxygen build.
 *
 * The \section markers provide \ref stubs for a3m, mage and ngin3d
 *************************************************************************/

/** \mainpage Advanced 3D Middleware - A3M

\section a3m Introduction

\image html title_page_01.png

A3M (Advanced 3D Middleware) is a compact and highly flexible 3D graphics engine
built on top of OpenGL ES 2.x.  It is specifically designed for use in embedded
environments.

A3M is an integral part of \ref mage, however, A3M is not dedicated to Android
and may be deployed on other OS's and platforms. The android Java API overlays a
native C++ API and A3M can be used in pure C++ environments. A3M fully supports
programmable-pipeline GPU graphics.


<h2>Reading List</h2>
\b Essential:
- \ref a3mPrimer

Recommended:
\ifnot DOX_A3M_JNI
- \ref a3mCpp
\endif
- \ref a3mJusr

Reference:
\ifnot DOX_A3M_JNI
- \ref a3mTech "A3M Maintainer's Technical Manual"
\endif
- \ref glossary

\section mage MAGE

This diagram illustrates where A3M fits into MAGE.  MAGE includes MediaTek's
Ngin3D 3D UI Framework for Android and support for both Adobe AfterEffects for
animation, and Autodesk 3DSMax for animated 3D models and scenes.

\image html mage_units_01.png "A3M as part of MAGE"

\section ngin3d Ngin3D

Ngin3d is MediaTek's Android 3D Graphics integration layer. It provides the
integration between the user's Android UI applications, Android infrastructure
(including threading, interpreting JSON animations generated by Adobe
AfterEffects, etc.), and A3M. Ngin3D is written in Java.

Documentation for the Java API used by Ngin3d is included \ref a3mJusr "here".
Documentation for Ngin3D is supplied separately.

<hr>

\note This documentation, and some of the code, uses a mixture of English
(<i>centre, colour</i>) and American (<i>center, color</i>) spellings.  Where
this is important within the code there may be an alias defined so that it
does not matter which you use, but this is not guaranteed.

*/

/*************************************************************************
 * Glossary entry point
 *************************************************************************/
/** \defgroup glossary Glossary

Glossary of terms.

*/


/* END OF FILE */


