/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode */

#ifndef _Included_com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode
#define _Included_com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_CLIENT_ERROR
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_CLIENT_ERROR 1400L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_FULLY_LOCK_FAILED
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_FULLY_LOCK_FAILED 1402L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_OPERATION_SUCCESSSFUL
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_OPERATION_SUCCESSSFUL 1200L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_PARTIALLY_LOCK_FAILED
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_PARTIALLY_LOCK_FAILED 1403L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_UNLOCK_FAILED
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_UNLOCK_FAILED 1404L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_USER_CANCELLED
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_USER_CANCELLED 1401L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_AND_ASSOCIATED_LIST_ITEMS_SUCCESSFUL
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_AND_ASSOCIATED_LIST_ITEMS_SUCCESSFUL 1202L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_FAILED
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_FAILED 1405L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_NOT_PERFORMED
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_NOT_PERFORMED 1406L
#undef com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_SUCCESSFUL
#define com_mediatek_MediatekDM_mdm_lawmo_LawmoResultCode_WIPE_DATA_SUCCESSFUL 1201L
#ifdef __cplusplus
}
#endif
#endif
