/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl */

#ifndef _Included_com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
#define _Included_com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_UNDEFINED_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_UNDEFINED_SCREEN 0L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_INITIAL_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_INITIAL_SCREEN 1L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_AUTH_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_AUTH_SCREEN 2L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_AUTH_FAIL_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_AUTH_FAIL_SCREEN 3L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_IN_SESSION_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_IN_SESSION_SCREEN 4L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_SERVER_INFO_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_SERVER_INFO_SCREEN 5L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_CONTINUE_ABORT_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_CONTINUE_ABORT_SCREEN 6L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_ENTER_DETAILS_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_ENTER_DETAILS_SCREEN 7L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_SINGLE_CHOICE_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_SINGLE_CHOICE_SCREEN 8L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_MULTIPLE_CHOICE_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_MULTIPLE_CHOICE_SCREEN 9L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_EXIT_FAIL_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_EXIT_FAIL_SCREEN 10L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_EXIT_OK_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_EXIT_OK_SCREEN 11L
#undef com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_SYNC_FAIL_SCREEN
#define com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl_OMC_MMI_SYNC_FAIL_SCREEN 12L
/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
 * Method:    notifyChoicelistSelection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine_00024MmiObserverImpl_notifyChoicelistSelection
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
 * Method:    notifyCancelEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine_00024MmiObserverImpl_notifyCancelEvent
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
 * Method:    notifyConfirmationResult
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine_00024MmiObserverImpl_notifyConfirmationResult
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
 * Method:    notifyInfoMsgClosed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine_00024MmiObserverImpl_notifyInfoMsgClosed
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
 * Method:    notifyInputResult
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine_00024MmiObserverImpl_notifyInputResult
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine_MmiObserverImpl
 * Method:    notifyTimeoutEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine_00024MmiObserverImpl_notifyTimeoutEvent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
