/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult */

#ifndef _Included_com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult
#define _Included_com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_ACTIVATE_FAILED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_ACTIVATE_FAILED 1409L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_AUTH_FAILED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_AUTH_FAILED 1403L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_CLIENT_ERROR
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_CLIENT_ERROR 1400L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DEACTIVATE_FAILED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DEACTIVATE_FAILED 1410L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DL_SERVER_ERROR
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DL_SERVER_ERROR 1500L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DL_SERVER_UNAVAILABLE
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DL_SERVER_UNAVAILABLE 1501L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DOWNLOAD_CANCELED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DOWNLOAD_CANCELED 1401L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DOWNLOAD_FAILED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_DOWNLOAD_FAILED 1402L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_INSTALL_FAILED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_INSTALL_FAILED 1405L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_NOT_IMPLEMENTED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_NOT_IMPLEMENTED 1411L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_OUT_OF_MEMORY_FOR_DOWNLOAD
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_OUT_OF_MEMORY_FOR_DOWNLOAD 1404L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_OUT_OF_MEMORY_FOR_INSTALL
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_OUT_OF_MEMORY_FOR_INSTALL 1406L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_REMOVE_FAILED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_REMOVE_FAILED 1408L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_SIGNATURE_FAILED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_SIGNATURE_FAILED 1407L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_SUCCESSFUL
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_SUCCESSFUL 1200L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_UNDEFINED_ERROR
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_UNDEFINED_ERROR 1412L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_UNSUPPORTED_ENV
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_UNSUPPORTED_ENV 1413L
#undef com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_USER_CANCELED
#define com_mediatek_MediatekDM_mdm_scomo_MdmScomoResult_USER_CANCELED 1401L
#ifdef __cplusplus
}
#endif
#endif
