/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_MediatekDM_mdm_MdmEngine */

#ifndef _Included_com_mediatek_MediatekDM_mdm_MdmEngine
#define _Included_com_mediatek_MediatekDM_mdm_MdmEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1create
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1start
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    isIdle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine_isIdle
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1stop
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _setConnectionTimeout
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1setConnectionTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _cancelSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1cancelSession
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _triggerNIADmSession
 * Signature: ([BLcom/mediatek/MediatekDM/mdm/SessionInitiator;Lcom/mediatek/MediatekDM/mdm/NIAMsgHandler;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1triggerNIADmSession
  (JNIEnv *, jobject, jbyteArray, jobject, jobject);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _triggerDMSession
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1triggerDMSession
  (JNIEnv *, jobject, jstring, jstring, jbyteArray);

/*
 * Class:     com_mediatek_MediatekDM_mdm_MdmEngine
 * Method:    _notifyNIASessionProceed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_MediatekDM_mdm_MdmEngine__1notifyNIASessionProceed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
