/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Quaternion */

#ifndef _Included_com_mediatek_a3m_Quaternion
#define _Included_com_mediatek_a3m_Quaternion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_Quaternion
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Quaternion_create__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Quaternion
 * Method:    create
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Quaternion_create__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mediatek_a3m_Quaternion
 * Method:    create
 * Signature: (Lcom/mediatek/a3m/Vector3;F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Quaternion_create__Lcom_mediatek_a3m_Vector3_2F
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Quaternion
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Quaternion_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Quaternion
 * Method:    times
 * Signature: (Lcom/mediatek/a3m/Quaternion;)Lcom/mediatek/a3m/Quaternion;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Quaternion_times
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Quaternion
 * Method:    toAxisAngle
 * Signature: ()Lcom/mediatek/a3m/Quaternion/AxisAngle;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Quaternion_toAxisAngle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
