/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Appearance_CullingMode */

#ifndef _Included_com_mediatek_a3m_Appearance_CullingMode
#define _Included_com_mediatek_a3m_Appearance_CullingMode
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mediatek_a3m_Appearance_CullingMode_CULL_BACK
#define com_mediatek_a3m_Appearance_CullingMode_CULL_BACK 0L
#undef com_mediatek_a3m_Appearance_CullingMode_CULL_FRONT
#define com_mediatek_a3m_Appearance_CullingMode_CULL_FRONT 1L
#undef com_mediatek_a3m_Appearance_CullingMode_CULL_FRONT_AND_BACK
#define com_mediatek_a3m_Appearance_CullingMode_CULL_FRONT_AND_BACK 2L
#undef com_mediatek_a3m_Appearance_CullingMode_CULL_NONE
#define com_mediatek_a3m_Appearance_CullingMode_CULL_NONE 3L
#ifdef __cplusplus
}
#endif
#endif
