/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Vector2 */

#ifndef _Included_com_mediatek_a3m_Vector2
#define _Included_com_mediatek_a3m_Vector2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector2_create__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    create
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector2_create__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector2_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    add
 * Signature: (Lcom/mediatek/a3m/Vector2;Lcom/mediatek/a3m/Vector2;)Lcom/mediatek/a3m/Vector2;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector2_add
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    subtract
 * Signature: (Lcom/mediatek/a3m/Vector2;Lcom/mediatek/a3m/Vector2;)Lcom/mediatek/a3m/Vector2;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector2_subtract
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    multiply
 * Signature: (Lcom/mediatek/a3m/Vector2;F)Lcom/mediatek/a3m/Vector2;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector2_multiply
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    divide
 * Signature: (Lcom/mediatek/a3m/Vector2;F)Lcom/mediatek/a3m/Vector2;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector2_divide
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    dot
 * Signature: (Lcom/mediatek/a3m/Vector2;Lcom/mediatek/a3m/Vector2;)F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector2_dot
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    length
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector2_length
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    normalize
 * Signature: ()Lcom/mediatek/a3m/Vector2;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector2_normalize
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    x
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector2_x__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    y
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector2_y__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    x
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector2_x__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector2
 * Method:    y
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector2_y__F
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
