/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_SceneUtility */

#ifndef _Included_com_mediatek_a3m_SceneUtility
#define _Included_com_mediatek_a3m_SceneUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_SceneUtility
 * Method:    createSquare
 * Signature: (Lcom/mediatek/a3m/AssetPool;Lcom/mediatek/a3m/Vector2;)Lcom/mediatek/a3m/Solid;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneUtility_createSquare
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_SceneUtility
 * Method:    createCube
 * Signature: (Lcom/mediatek/a3m/AssetPool;Lcom/mediatek/a3m/Vector2;)Lcom/mediatek/a3m/Solid;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneUtility_createCube
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_SceneUtility
 * Method:    createSphere
 * Signature: (Lcom/mediatek/a3m/AssetPool;FFLcom/mediatek/a3m/Vector2;)Lcom/mediatek/a3m/Solid;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneUtility_createSphere
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jobject);

/*
 * Class:     com_mediatek_a3m_SceneUtility
 * Method:    pointAt
 * Signature: (Lcom/mediatek/a3m/SceneNode;Lcom/mediatek/a3m/Vector3;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneUtility_pointAt__Lcom_mediatek_a3m_SceneNode_2Lcom_mediatek_a3m_Vector3_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_SceneUtility
 * Method:    pointAt
 * Signature: (Lcom/mediatek/a3m/SceneNode;Lcom/mediatek/a3m/SceneNode;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneUtility_pointAt__Lcom_mediatek_a3m_SceneNode_2Lcom_mediatek_a3m_SceneNode_2
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
