/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Camera */

#ifndef _Included_com_mediatek_a3m_Camera
#define _Included_com_mediatek_a3m_Camera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_Camera
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Camera_create
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Camera
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Camera_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Camera
 * Method:    setFov
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Camera_setFov
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Camera
 * Method:    setNear
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Camera_setNear
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Camera
 * Method:    setFar
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Camera_setFar
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Camera
 * Method:    setStereo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Camera_setStereo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_mediatek_a3m_Camera
 * Method:    getProjection
 * Signature: (F)Lcom/mediatek/a3m/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Camera_getProjection
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
