/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Solid */

#ifndef _Included_com_mediatek_a3m_Solid
#define _Included_com_mediatek_a3m_Solid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_Solid
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Solid_create
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Solid
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Solid_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Solid
 * Method:    getAppearance
 * Signature: ()Lcom/mediatek/a3m/Appearance;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Solid_getAppearance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
