/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_NativeObject */

#ifndef _Included_com_mediatek_a3m_NativeObject
#define _Included_com_mediatek_a3m_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_NativeObject
 * Method:    classInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_NativeObject_classInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_a3m_NativeObject
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_NativeObject_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
