/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_AnimationGroup */

#ifndef _Included_com_mediatek_a3m_AnimationGroup
#define _Included_com_mediatek_a3m_AnimationGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_AnimationGroup
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_AnimationGroup_create
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_AnimationGroup
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_AnimationGroup_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_AnimationGroup
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_AnimationGroup_update
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_AnimationGroup
 * Method:    length
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_AnimationGroup_length
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_AnimationGroup
 * Method:    setLooping
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_AnimationGroup_setLooping
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mediatek_a3m_AnimationGroup
 * Method:    start
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_AnimationGroup_start
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_AnimationGroup
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_AnimationGroup_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
