/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Renderer */

#ifndef _Included_com_mediatek_a3m_Renderer
#define _Included_com_mediatek_a3m_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_Renderer
 * Method:    create
 * Signature: (Lcom/mediatek/a3m/AssetPool;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Renderer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Renderer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Renderer_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Renderer
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Renderer_clear
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_a3m_Renderer
 * Method:    getPixels
 * Signature: (IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mediatek_a3m_Renderer_getPixels
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_mediatek_a3m_Renderer
 * Method:    render
 * Signature: (Lcom/mediatek/a3m/Camera;Lcom/mediatek/a3m/SceneNode;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Renderer_render
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Renderer
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Renderer_update
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
