/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Appearance */

#ifndef _Included_com_mediatek_a3m_Appearance
#define _Included_com_mediatek_a3m_Appearance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_create
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setProperty
 * Signature: (Ljava/lang/String;Lcom/mediatek/a3m/Vector4;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setProperty__Ljava_lang_String_2Lcom_mediatek_a3m_Vector4_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setProperty
 * Signature: (Ljava/lang/String;Lcom/mediatek/a3m/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setProperty__Ljava_lang_String_2Lcom_mediatek_a3m_Texture2D_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    getPropertyVector4
 * Signature: (Ljava/lang/String;)Lcom/mediatek/a3m/Vector4;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Appearance_getPropertyVector4
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setBlendFactors
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setBlendFactors
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setDepthWriteEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setDepthWriteEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setScissorTestEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setScissorTestEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setScissorRectangle
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setScissorRectangle
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setShaderProgram
 * Signature: (Lcom/mediatek/a3m/AssetPool;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setShaderProgram
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    setCullingMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Appearance_setCullingMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_a3m_Appearance
 * Method:    getCullingMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_Appearance_getCullingMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
