/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Vector3 */

#ifndef _Included_com_mediatek_a3m_Vector3
#define _Included_com_mediatek_a3m_Vector3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector3_create__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    create
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector3_create__FFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector3_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    add
 * Signature: (Lcom/mediatek/a3m/Vector3;Lcom/mediatek/a3m/Vector3;)Lcom/mediatek/a3m/Vector3;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector3_add
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    subtract
 * Signature: (Lcom/mediatek/a3m/Vector3;Lcom/mediatek/a3m/Vector3;)Lcom/mediatek/a3m/Vector3;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector3_subtract
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    multiply
 * Signature: (Lcom/mediatek/a3m/Vector3;F)Lcom/mediatek/a3m/Vector3;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector3_multiply
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    divide
 * Signature: (Lcom/mediatek/a3m/Vector3;F)Lcom/mediatek/a3m/Vector3;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector3_divide
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    dot
 * Signature: (Lcom/mediatek/a3m/Vector3;Lcom/mediatek/a3m/Vector3;)F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector3_dot
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    length
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector3_length
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    normalize
 * Signature: ()Lcom/mediatek/a3m/Vector3;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_Vector3_normalize
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    x
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector3_x__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    y
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector3_y__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    z
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mediatek_a3m_Vector3_z__
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    x
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector3_x__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    y
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector3_y__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mediatek_a3m_Vector3
 * Method:    z
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Vector3_z__F
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
