/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_Texture2D */

#ifndef _Included_com_mediatek_a3m_Texture2D
#define _Included_com_mediatek_a3m_Texture2D
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mediatek_a3m_Texture2D_FORMAT_RGBA
#define com_mediatek_a3m_Texture2D_FORMAT_RGBA 0L
#undef com_mediatek_a3m_Texture2D_FORMAT_RGB
#define com_mediatek_a3m_Texture2D_FORMAT_RGB 1L
#undef com_mediatek_a3m_Texture2D_FORMAT_LUMINANCE_ALPHA
#define com_mediatek_a3m_Texture2D_FORMAT_LUMINANCE_ALPHA 2L
#undef com_mediatek_a3m_Texture2D_FORMAT_LUMINANCE
#define com_mediatek_a3m_Texture2D_FORMAT_LUMINANCE 3L
#undef com_mediatek_a3m_Texture2D_FORMAT_ALPHA
#define com_mediatek_a3m_Texture2D_FORMAT_ALPHA 4L
#undef com_mediatek_a3m_Texture2D_FORMAT_DEPTH
#define com_mediatek_a3m_Texture2D_FORMAT_DEPTH 5L
#undef com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_BYTE
#define com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_BYTE 0L
#undef com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT
#define com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT 1L
#undef com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT_4_4_4_4
#define com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT_4_4_4_4 2L
#undef com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT_5_5_5_1
#define com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT_5_5_5_1 3L
#undef com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT_5_6_5
#define com_mediatek_a3m_Texture2D_TYPE_UNSIGNED_SHORT_5_6_5 4L
#undef com_mediatek_a3m_Texture2D_WRAP_MODE_REPEAT
#define com_mediatek_a3m_Texture2D_WRAP_MODE_REPEAT 0L
#undef com_mediatek_a3m_Texture2D_WRAP_MODE_CLAMP
#define com_mediatek_a3m_Texture2D_WRAP_MODE_CLAMP 1L
#undef com_mediatek_a3m_Texture2D_WRAP_MODE_MIRROR
#define com_mediatek_a3m_Texture2D_WRAP_MODE_MIRROR 2L
#undef com_mediatek_a3m_Texture2D_FILTER_MODE_NEAREST
#define com_mediatek_a3m_Texture2D_FILTER_MODE_NEAREST 0L
#undef com_mediatek_a3m_Texture2D_FILTER_MODE_LINEAR
#define com_mediatek_a3m_Texture2D_FILTER_MODE_LINEAR 1L
#undef com_mediatek_a3m_Texture2D_FILTER_MODE_NEAREST_MIPMAP_NEAREST
#define com_mediatek_a3m_Texture2D_FILTER_MODE_NEAREST_MIPMAP_NEAREST 2L
#undef com_mediatek_a3m_Texture2D_FILTER_MODE_NEAREST_MIPMAP_LINEAR
#define com_mediatek_a3m_Texture2D_FILTER_MODE_NEAREST_MIPMAP_LINEAR 3L
#undef com_mediatek_a3m_Texture2D_FILTER_MODE_LINEAR_MIPMAP_NEAREST
#define com_mediatek_a3m_Texture2D_FILTER_MODE_LINEAR_MIPMAP_NEAREST 4L
#undef com_mediatek_a3m_Texture2D_FILTER_MODE_LINEAR_MIPMAP_LINEAR
#define com_mediatek_a3m_Texture2D_FILTER_MODE_LINEAR_MIPMAP_LINEAR 5L
/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Texture2D_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    setHorizontalWrap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Texture2D_setHorizontalWrap
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    getHorizontalWrap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_Texture2D_getHorizontalWrap
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    setVerticalWrap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Texture2D_setVerticalWrap
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    getVerticalWrap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_Texture2D_getVerticalWrap
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_Texture2D_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_Texture2D_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    setMinFilter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Texture2D_setMinFilter
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    getMinFilter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_Texture2D_getMinFilter
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    setMagFilter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_Texture2D_setMagFilter
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_a3m_Texture2D
 * Method:    getMagFilter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_Texture2D_getMagFilter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
