/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_a3m_SceneNode */

#ifndef _Included_com_mediatek_a3m_SceneNode
#define _Included_com_mediatek_a3m_SceneNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_create
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    hashCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_SceneNode_hashCode
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mediatek_a3m_SceneNode_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    setParent
 * Signature: (Lcom/mediatek/a3m/SceneNode;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_setParent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    find
 * Signature: (Ljava/lang/String;)Lcom/mediatek/a3m/SceneNode;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneNode_find
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    setPosition
 * Signature: (Lcom/mediatek/a3m/Vector3;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_setPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getPosition
 * Signature: ()Lcom/mediatek/a3m/Vector3;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneNode_getPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    setRotation
 * Signature: (Lcom/mediatek/a3m/Quaternion;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_setRotation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getRotation
 * Signature: ()Lcom/mediatek/a3m/Quaternion;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneNode_getRotation
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    setScale
 * Signature: (Lcom/mediatek/a3m/Vector3;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_setScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getScale
 * Signature: ()Lcom/mediatek/a3m/Vector3;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneNode_getScale
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getWorldTransform
 * Signature: ()Lcom/mediatek/a3m/Matrix4;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneNode_getWorldTransform
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getChildCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_SceneNode_getChildCount
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getChild
 * Signature: (I)Lcom/mediatek/a3m/SceneNode;
 */
JNIEXPORT jobject JNICALL Java_com_mediatek_a3m_SceneNode_getChild
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getVisibilityFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_a3m_SceneNode_getVisibilityFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_a3m_SceneNode_isVisible
  (JNIEnv *, jobject);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    setVisibilityFlag
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_setVisibilityFlag
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    setRenderLayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_a3m_SceneNode_setRenderLayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mediatek_a3m_SceneNode
 * Method:    getRenderLayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_a3m_SceneNode_getRenderLayer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
