/*
* Copyright (C) 2007 The Android Open Source Project
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package com.android.emailcommon.utility;

import java.util.regex.Pattern;
import android.os.SystemProperties;

/**
* Commonly used regular expression patterns.
*/
public class CustomPattern {

    public static final boolean IS_CMCC =
        (SystemProperties.get("ro.operator.optr") != null && SystemProperties.get("ro.operator.optr").equals("OP01"));

   /**
    *  Regular expression to match all IANA top-level domains for WEB_URL.
    *  List accurate as of 2010/02/05.  List taken from:
    *  http://data.iana.org/TLD/tlds-alpha-by-domain.txt
    *  This pattern is auto-generated by frameworks/base/common/tools/make-iana-tld-pattern.py
    */
   public static final String TOP_LEVEL_DOMAIN_STR_FOR_WEB_URL =
       "(?:"
       + "(?:aero|arpa|asia|a[cdefgilmnoqrstuwxz])"
       + "|(?:biz|b[abdefghijmnorstvwyz])"
       + "|(?:cat|com|coop|c[acdfghiklmnoruvxyz])"
       + "|d[ejkmoz]"
       + "|(?:edu|e[cegrstu])"
       + "|f[ijkmor]"
       + "|(?:gov|g[abdefghilmnpqrstuwy])"
       + "|h[kmnrtu]"
       + "|(?:info|int|i[delmnoqrst])"
       + "|(?:jobs|j[emop])"
       + "|k[eghimnprwyz]"
       + "|l[abcikrstuvy]"
       + "|(?:mil|mobi|museum|m[acdeghklmnopqrstuvwxyz])"
       + "|(?:name|net|n[acefgilopruz])"
       + "|(?:org|om)"
       + "|(?:pro|p[aefghklmnrstwy])"
       + "|qa"
       + "|r[eosuw]"
       + "|s[abcdeghijklmnortuvyz]"
       + "|(?:tel|travel|t[cdfghjklmnoprtvwz])"
       + "|u[agksyz]"
       + "|v[aceginu]"
       + "|w[fs]"
       + "|(?:xn\\-\\-0zwm56d|xn\\-\\-11b5bs3a9aj6g|xn\\-\\-80akhbyknj4f|xn\\-\\-9t4b11yi5a|xn\\-\\-deba0ad|xn\\-\\-g6w251d|xn\\-\\-hgbk6aj7f53bba|xn\\-\\-hlcj6aya9esc7a|xn\\-\\-jxalpdlp|xn\\-\\-kgbechtv|xn\\-\\-zckzah)"
       + "|y[etu]"
       + "|z[amw]))";

   /**
    * Much weak regular expression, only parse the following domain.
    */
   public static final String TOP_LEVEL_DOMAIN_STR_FOR_WEB_URL_2 =
       "(?:" +
       "(?:com.tw|com.cn|com.hk|com|cc|cn|coop)" + 
       "|(?:eu|edu.cn)" + 
       "|(?:gov.cn)" + 
       "|(?:hk)" +
       "|(?:io|info|in|it)" +
       "|(?:jp|jobs)" +
       "|(?:la|ltd.uk)" +
       "|(?:me.uk|mobi)" +
       "|(?:name|net)" +
       "|(?:org.uk|org)" +
       "|(?:plc.uk)" +
       "|(?:tv|tw|travel|tel)" +
       "|(?:us)))";

   /**
    * Good characters for Internationalized Resource Identifiers (IRI).
    * This comprises most common used Unicode characters allowed in IRI
    * as detailed in RFC 3987.
    * Specifically, those two byte Unicode characters are not included.
    */
   public static final String GOOD_IRI_CHAR =
       "a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF";
   
   /**
    * only support English url, as Unicode url will not highlight correctly
    */
   public static final String ENG_IRI_CHAR = "a-zA-Z0-9";

   /**
    *  Regular expression pattern to match most part of RFC 3987
    *  Internationalized URLs, aka IRIs.  Commonly used Unicode characters are
    *  added.
    */
   public static final Pattern WEB_URL = 
           Pattern.compile(
                   "((?:(http|https|Http|Https|rtsp|Rtsp):\\/\\/(?:(?:[a-zA-Z0-9\\$\\-\\_\\.\\+\\!\\*\\'\\(\\)"
                   + "\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,64}(?:\\:(?:[a-zA-Z0-9\\$\\-\\_"
                   + "\\.\\+\\!\\*\\'\\(\\)\\,\\;\\?\\&\\=]|(?:\\%[a-fA-F0-9]{2})){1,25})?\\@)?)?"
                   + "((?:(?:[" + ENG_IRI_CHAR + "][" + ENG_IRI_CHAR + "\\-]{0,64}\\.)+"   // named host
                   + TOP_LEVEL_DOMAIN_STR_FOR_WEB_URL_2
                   + "|(?:(?:25[0-5]|2[0-4]" // or ip address
                   + "[0-9]|[0-1][0-9]{2}|[1-9][0-9]|[1-9])\\.(?:25[0-5]|2[0-4][0-9]"
                   + "|[0-1][0-9]{2}|[1-9][0-9]|[1-9]|0)\\.(?:25[0-5]|2[0-4][0-9]|[0-1]"
                   + "[0-9]{2}|[1-9][0-9]|[1-9]|0)\\.(?:25[0-5]|2[0-4][0-9]|[0-1][0-9]{2}"
                   + "|[1-9][0-9]|[0-9])))"
                   + "(?:\\:\\d{1,5})?)" // plus option port number
                   + "(\\/(?:(?:[" + GOOD_IRI_CHAR + "\\;\\/\\?\\:\\@\\&\\=\\#\\~"  // plus option query params
                   + "\\-\\.\\+\\!\\*\\'\\(\\)\\_])|(?:\\%[a-fA-F0-9]{2}))*)?"); //change for CMCC URL rule.

}
